{
    'name': 'Sales & Project Lifecycle Management',
    'version': '19.0.1.0.0',
    'category': 'Sales',
    'summary': 'Team-based sales, deal pricing, commission, project, QC and client service lifecycle',
    'description': """
Sales & Project Lifecycle Management (Otomater)
================================================
Phase 1: Sales teams, Sales Heads / Executives, strict record-rule isolation,
service master, lead sources, leads and lead service lines.
""",
    'author': 'Otomater',
    'website': 'https://otomater.com',
    'license': 'OPL-1',
    'depends': ['base', 'mail', 'project'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/default_data.xml',
        'data/cron.xml',
        'data/mail_templates.xml',
        'data/message_templates.xml',
        'views/sales_team_views.xml',
        'views/service_views.xml',
        'views/lead_views.xml',
        'views/message_template_views.xml',
        'views/demo_views.xml',
        'views/estimate_views.xml',
        'views/reason_wizard_views.xml',
        'views/deal_views.xml',
        'views/commission_views.xml',
        'views/agreement_views.xml',
        'views/project_views.xml',
        'views/qc_views.xml',
        'views/training_views.xml',
        'views/review_views.xml',
        'views/client_service_views.xml',
        'report/agreement_report.xml',
        'report/estimate_report.xml',
        'views/res_config_settings_views.xml',
        'views/lead_lost_wizard_views.xml',
        'views/transition_log_views.xml',
        'views/res_users_views.xml',
        'views/menus.xml',
        'views/dashboard_views.xml',
        'views/report_views.xml',
    ],
    'demo': [
        'demo/demo_data.xml',
        'demo/demo_lifecycle.xml',
    ],
    'application': True,
    'assets': {
        'web.assets_backend': [
            'sales_project_lifecycle/static/src/scss/otm_dashboard.scss',
            'sales_project_lifecycle/static/src/js/dashboard.js',
            'sales_project_lifecycle/static/src/js/project_board.js',
            'sales_project_lifecycle/static/src/js/customer360.js',
            'sales_project_lifecycle/static/src/js/stage_tracker.js',
            'sales_project_lifecycle/static/src/xml/otm_templates.xml',
        ],
    },
    'installable': True,
}
