from . import test_sales_team_security
from . import test_services
from . import test_lead_transitions
from . import test_demo
from . import test_estimate
from . import test_deal_commission
from . import test_agreement_finance
from . import test_project
from . import test_qc_deployment
from . import test_training
from . import test_closure
from . import test_client_services
from . import test_dashboard
from . import test_phase11
